name: Monitoramento Mensal da Gentrificação no Rio de Janeiro

on:
  schedule:
    - cron: '0 0 28  * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar codigo do repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar bibliotecas
        run: pip install -r requirements.txt

      - name: Executar Scraping e Limpeza
        run: python main.py

      - name: Atualizar Banco de Dados
        run: |
          git config --global user.name "LauroGobatto"
          git config --global user.email "lauroz1232@gmail.com"
          git add .
          git commit -m "Dados atualizados automaticamente"
          git push